.TH "netw4ppl.ines.MainActivity" 3 "Mon Jun 7 2021" "Version 1.0.3" "Netw4ppl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netw4ppl.ines.MainActivity
.SH SYNOPSIS
.br
.PP
.PP
Inherits AppCompatActivity\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBloadConfiguration\fP (Context context)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static String \fBdevice_language\fP"
.br
.ti -1c
.RI "static boolean \fBmApplicationLaunch\fP = true"
.br
.ti -1c
.RI "static \fBConfiguration\fP \fBmConfiguration\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.ti -1c
.RI "void \fBonStart\fP ()"
.br
.ti -1c
.RI "void \fBonStop\fP ()"
.br
.ti -1c
.RI "void \fBonResume\fP ()"
.br
.ti -1c
.RI "void \fBonPause\fP ()"
.br
.ti -1c
.RI "void \fBonDestroy\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file MainActivity\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void netw4ppl\&.ines\&.MainActivity\&.loadConfiguration (Context context)\fC [static]\fP"
Function to load the configuration and read all the jsons files\&.
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP the application context 
.RE
.PP

.PP
Definition at line 136 of file MainActivity\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Netw4ppl from the source code\&.
