.TH "netw4ppl.ines.SettingsActivity" 3 "Mon Jun 7 2021" "Version 1.0.3" "Netw4ppl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netw4ppl.ines.SettingsActivity
.SH SYNOPSIS
.br
.PP
.PP
Inherits AppCompatActivity\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSettingsFragment\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBrecursiveSetSingleLine\fP (PreferenceGroup screen, EditTextPreference\&.OnBindEditTextListener noMultilineAllowed)"
.br
.ti -1c
.RI "static void \fBdisplayToast\fP (Context contextA, CharSequence textToast)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.ti -1c
.RI "void \fBonStart\fP ()"
.br
.ti -1c
.RI "void \fBonStop\fP ()"
.br
.ti -1c
.RI "void \fBonResume\fP ()"
.br
.ti -1c
.RI "void \fBonPause\fP ()"
.br
.ti -1c
.RI "void \fBonDestroy\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file SettingsActivity\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void netw4ppl\&.ines\&.SettingsActivity\&.displayToast (Context contextA, CharSequence textToast)\fC [static]\fP"
Function to display a toast based on a context and a text
.PP
\fBParameters\fP
.RS 4
\fIcontextA\fP the application context 
.br
\fItextToast\fP the text to be displayed in the toast 
.RE
.PP

.PP
Definition at line 194 of file SettingsActivity\&.java\&.
.SS "static void netw4ppl\&.ines\&.SettingsActivity\&.recursiveSetSingleLine (PreferenceGroup screen, EditTextPreference\&.OnBindEditTextListener noMultilineAllowed)\fC [static]\fP"
Recursive function to set all the inputs on a single line\&.
.PP
\fBParameters\fP
.RS 4
\fIscreen\fP a PreferenceGroup object 
.br
\fInoMultilineAllowed\fP 
.RE
.PP

.PP
Definition at line 174 of file SettingsActivity\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Netw4ppl from the source code\&.
