.TH "netw4ppl.ines.DisplayDetailsRelationActivity" 3 "Mon Jun 7 2021" "Version 1.0.3" "Netw4ppl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netw4ppl.ines.DisplayDetailsRelationActivity
.SH SYNOPSIS
.br
.PP
.PP
Inherits AppCompatActivity\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.ti -1c
.RI "void \fBonResume\fP ()"
.br
.ti -1c
.RI "void \fBonSaveInstanceState\fP (@NonNull Bundle outState)"
.br
.ti -1c
.RI "void \fBonRestoreInstanceState\fP (@NonNull Bundle savedInstanceState)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class used to display the details about a relation like the ids and names of the person associated, the relation type and finally the comments about this relation if there are any\&. 
.PP
Definition at line 29 of file DisplayDetailsRelationActivity\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Netw4ppl from the source code\&.
